FROM node:11

# creamos directorio de destino
RUN mkdir -p /usr/src/BaseApp_VUE_IRAV
WORKDIR /usr/src/BaseApp_VUE_IRAV

# actualizamos e instalamos dependencias

RUN apt update && apt upgrade -y

# copiamos la app, note .dockerignore

COPY . /usr/src/BaseApp_VUE_IRAV
RUN npm install

# Ejecutamos en modo BUILD

RUN npm run build

# exponer puerto de Container
EXPOSE 5000

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=5000

# start the app
CMD [ "npm", "start" ]